default:
  font: Helvetica
  bold: "{* Bold}"
  mono: Andale Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  bookname: "MarkdownBook"
  thanks: "Edit latex/config.yml : \\url{http://your.domain}"
en:
  font: Helvetica
  bold: "{* Bold}"
  mono: Andale Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "Edit latex/config.yml : \\url{http://your.domain}"
  bookname: "MarkdownBook"
zh:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: STHeiti
  bold: STHeiti
  mono: STHeiti
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "节"
  con: "目录"
  fig: "图 "
  tab: "表 "
  indent: "文"
  bookname: "MarkdownBook"
zh-tw:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: AR PL UMing TW
  bold: AR PL UKai TW
  mono: AR PL UKai TW
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目錄"
  fig: "圖 "
  tab: "表 "
  indent: "文"
ja:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
#  font: Japan
#  font: Sazanami Mincho
  font: IPAPMincho
  bold: VL PGothic
#  bold: Sazanami Gothic
#  bold: IPAPGothic
  mono: VL Gothic
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目次"
  fig: "図"
  tab: "表"
  indent: "あ"
ru:
  prechap: "Глава "
  presect: "Раздел "
  con: "Содержание"
  fig: "Рисунок "
  tab: "Таблица "
  dql: "«"
  dqr: "»"
  langrule: "\\frenchspacing"
cs:
  prechap: "Kapitola "
  presect: "Oddíl "
  dql: "„"
  dqr: "“"
  fig: "Obrázek "
  tab: "Tabulka "
fr:
  prechap: "Chapitre "
  presect: "Section "
  fig: "figure "
  tab: "Tableau "
  font: Linux Libertine
  mono: Courier New
  con: "Table des matières"
  langrule: "\\frenchspacing\\usepackage{fontspec}\n\\fontspec[Ligatures={Common}]{Linux Libertine}\n"
  dql: "«\\,"
  dqr: "\\,»"
es:
  prechap: "Capítulo "
  presect: "Sección "
  fig: "Figura "
  tab: "Tabla "
  con: "Contenidos "  
mk:
  fig: "Слика"
  con: "Содржина"
  prechap: "Поглавје"
  presect: "Секција"
  dql: "„"
  dqr: "“"
  tab: "Табела"
no-nb:
  dql: "«"
  dqr: "»"
de:
  langrule: "\\frenchspacing"
  dql: "„"
  dqr: "“"
ko:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: NanumMyeongjo
  bold: "{* Bold}"
  mono: NanumGothicCoding 
  prechap: ""
  postchap: "장"
  presect: ""
  postsect: "절"
  indent: " "
  con: "목차"
  fig: "그림"
  tab: "표"
be:
  prechap: "Глава "
  presect: "Раздзел "
  con: "Змест"
  fig: "Малюнак "
  tab: "Табліца "
