default:
  font: Helvetica
  bold: "{* Bold}"
  mono: Andale Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  bookname: "MarkdownBook"
  thanks: "Customize your own thanks with editting latex/config.yml : \\url{http://your.domain}"
zh:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: STHeiti
  bold: STHeiti
  mono: STHeiti
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "节"
  con: "目录"
  fig: "图 "
  tab: "表 "
  indent: "文"
  bookname: "MarkdownBook"
zh-tw:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: AR PL UMing TW
  bold: AR PL UKai TW
  mono: AR PL UKai TW
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目錄"
  fig: "圖 "
  tab: "表 "
  indent: "文"
ja:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
#  font: Japan
#  font: Sazanami Mincho
  font: IPAPMincho
  bold: VL PGothic
#  bold: Sazanami Gothic
#  bold: IPAPGothic
  mono: VL Gothic
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目次"
  fig: "図"
  tab: "表"
  indent: "あ"
ru:
  prechap: "Глава "
  presect: "Раздел "
  con: "Содержание"
  fig: "Рисунок "
  tab: "Таблица "
  dql: "«"
  dqr: "»"
  langrule: "\\frenchspacing"
  thanks: "Это PDF-версия книги Pro Git. Текст книги находится под лицензией Creative Commons Attribution-Non Commercial-Share Alike 3.0. Надеемся, она вам понравится и поможет изучить Git. Если хотите, можете поддержать автора и Apress, купив бумажную версию книги на английском языке на Amazon: \\url{http://tinyurl.com/amazonprogit}.\\newline На сайте перевода книги на русский язык, расположенного по адресу \\url{https://github.com/GArik/progit/wiki}, можно проверить наличие новых версий книги, оставить сообщение об ошибке в тексте, а также скачать книгу в других форматах."
cs:
  prechap: "Kapitola "
  presect: "Oddíl "
  dql: "„"
  dqr: "“"
  fig: "Obrázek "
  tab: "Tabulka "
fr:
  prechap: "Chapitre "
  presect: "Section "
  fig: "figure "
  tab: "Tableau "
  font: Linux Libertine
  mono: Courier New
  con: "Table des matières"
  langrule: "\\frenchspacing\\usepackage{fontspec}\n\\fontspec[Ligatures={Common}]{Linux Libertine}\n"
  thanks: "Ce fichier PDF est la traduction française du livre Pro Git. Il est publié sous license Creative Commons Attribution-Non Commercial-Share Alike 3.0. J'espère que vous l'apprécierez, qu'il vous permettra d'apprendre à utiliser Git et que vous aiderez Apress en achetant le livre original sur Amazon : \\url{http://tinyurl.com/amazonprogit}"
  dql: "«\\,"
  dqr: "\\,»"
es:
  prechap: "Capítulo "
  presect: "Sección "
  fig: "Figura "
  tab: "Tabla "
  con: "Contenidos "  
mk:
  fig: "Слика"
  con: "Содржина"
  prechap: "Поглавје"
  presect: "Секција"
  dql: "„"
  dqr: "“"
  tab: "Табела"
no-nb:
  dql: "«"
  dqr: "»"
  thanks: "Dette er PDF filen for innholdet til boken Pro Git. Den er lisensiert under Creative Commons Attribution-Non Commercial-Share Alike 3.0 lisensen. Jeg håper du vil ha nytte av den, jeg håper den vil hjelpe deg til å lære Git, og jeg håper du vil støtte Apress og meg ved å kjøpe en kopi av denne boken hos Amazon: \\url{http://tinyurl.com/amazonprogit}"
de:
  langrule: "\\frenchspacing"
  dql: "„"
  dqr: "“"
ko:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: NanumMyeongjo
  bold: "{* Bold}"
  mono: NanumGothicCoding 
  prechap: ""
  postchap: "장"
  presect: ""
  postsect: "절"
  indent: " "
  con: "목차"
  fig: "그림"
  tab: "표"
  thanks: "지금 보시는 문서는 Pro Git 책에 대한 PDF 파일입니다. 본 문서는 Creative Commons 저작자표시-비영리조건-동일조건변경허락 3.0(Creative Commons Attribution-Non Commercial-Share Alike 3.0) 라이센스를 따릅니다. 여러분이 Git을 이해하는데 도움이 되기를 희망합니다. 종이로 출판된 책을 Amazon 웹사이트 \\url{http://tinyurl.com/amazonprogit} 에서 구입하여 저를 비롯한 Apress에도 도움을 주시기를 기대하겠습니다.\\newline한국어 번역은 박창우(pismute@gmail.com), 이성환(lethee@gmail.com)이 하였습니다. 오역 등의 개선 사항은 역자의 메일로 보내주시거나 한국어 번역 게시판에 \\url{https://github.com/dogfeet/progit/issues} 남겨주시기 바랍니다. 직접 개선해서 패치나 Pull Request를 보내주셔도 됩니다."
be:
  prechap: "Глава "
  presect: "Раздзел "
  con: "Змест"
  fig: "Малюнак "
  tab: "Табліца "
